"""atualizando tabela

Revision ID: 16af576b51f5
Revises: ae59fc507e27
Create Date: 2026-04-30 18:40:03.302439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16af576b51f5'
down_revision = 'ae59fc507e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capa', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estantes', schema=None) as batch_op:
        batch_op.drop_column('capa')

    # ### end Alembic commands ###
