"""atualizando tabela

Revision ID: 274d1e168433
Revises: 16af576b51f5
Create Date: 2026-05-08 19:22:21.033501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274d1e168433'
down_revision = '16af576b51f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livros', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
