"""atualizando tabela

Revision ID: 78ddbfb97407
Revises: 274d1e168433
Create Date: 2026-05-08 19:48:55.982874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ddbfb97407'
down_revision = '274d1e168433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estantes', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
