"""atualizar tabelas

Revision ID: ae59fc507e27
Revises: bb8bc4e0d182
Create Date: 2026-04-25 17:36:36.451195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae59fc507e27'
down_revision = 'bb8bc4e0d182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capa', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livros', schema=None) as batch_op:
        batch_op.drop_column('capa')

    # ### end Alembic commands ###
