"""criando tabelas

Revision ID: d04781111bce
Revises: 
Create Date: 2026-04-21 16:18:03.257678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04781111bce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('type_user', sa.Enum('admin', 'user'), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('estantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('arquivo_path', sa.String(length=255), nullable=False),
    sa.Column('favorito', sa.Boolean(), nullable=True),
    sa.Column('estante_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estante_id'], ['estantes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anotacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('data_acesso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marcacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto_extraido', sa.Text(), nullable=False),
    sa.Column('num_pagina', sa.Integer(), nullable=False),
    sa.Column('cor_destaque', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progressos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ultima_pagina', sa.Integer(), nullable=True),
    sa.Column('total_paginas', sa.Integer(), nullable=True),
    sa.Column('percentual_concluido', sa.Float(), nullable=True),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progressos')
    op.drop_table('marcacoes')
    op.drop_table('historicos')
    op.drop_table('anotacoes')
    op.drop_table('livros')
    op.drop_table('estantes')
    op.drop_table('user')
    # ### end Alembic commands ###
